### ISSUE TITLE
Some patch PRs and crates.io submission

### ISSUE THREAD

**Issue by fluffysquirrels** [equalsraf/webdriver#2]
I really liked the foundation of WebDriver client support that this crate offers and ended up starting an [experimental fork](https://github.com/fluffysquirrels/webdriver_client_rust/commits/master) that hackily patched a few things for my project's use. Would you be interested in seeing some tidied up pull requests with my changes?

I'd also love to see a WebDriver **client** on crates.io ([there is none at present](https://crates.io/search?q=webdriver)). Would you be interested in publishing this crate to crates.io to publicise it further? If not I'd be happy to do so.

Look forward to hearing from you, Alex.

**Comment by equalsraf** [comment]
To be honest I have not worked on this for a good while now - I ended up focusing in firefox instead because webdriver did not support some of the features I wanted - https://github.com/equalsraf/ffcli was what came out of it.

I currently lack the time to take in more work, so feel free to take over this and please do put it in crates.io

Some followup points:

- I had some pending changes here that I just pushed into the wip branch https://github.com/equalsraf/webdriver/pull/3 there is a lot of overlap with your changes :D
- I have nothing resembling serious tests for this crate, https://github.com/equalsraf/ffcli has some working CI tests for various things that might fit here e.g. starting a headless browser to run tests. Also a lot of other firefox specific bits.
- Despite my lack of time to push this forward, I'd love to see something like this working. Feel free to ping me if you want to discuss some issues (... I might take a while to respond :S).

**Comment by fluffysquirrels** [comment]
Thanks for your reply and for letting me build on your work. I'll try and remember to send you a message if I come up against any design questions or want a review!

I've glanced through your changes and they look great. I will work on merging them soon.

Yes, it would be very useful to have more tests, which I'd like to use our own checked in HTML so we don't depend on external sites.

**Comment by fluffysquirrels** [comment]
I've merged your changes and pushed the first version to [crates.io](https://crates.io/crates/webdriver_client). There's an integration test in there based on a static HTML file. Feedback welcome!
